name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: yarn build
      - run: yarn lint
      - run: yarn test
      - name: List files in the repository
      - run: echo "${{ job.status }}."
